pipelines:
  - name:    distribution
    steps:
      - name: Create_ReleaseBundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName:        Demo_RB
          releaseBundleVersion:     V1.0.${run_number}
          dryRun:                   false
          sign:                     true
          storeAtSourceArtifactory: aritfactory
          inputResources:
            - name:                docker_gradleBuild_Info
            - name:                docker_npmBuild_Info
          outputResources:
            - name:                New_ReleaseBundle
          description:              RB of gradle and npm build
          releaseNotes:
            syntax:                 markdown
            content: |
              ## Heading
                * Bullet
                * Points


#      - name: Sign_ReleaseBundle
#        type: SignReleaseBundle
#        configuration:
#          inputResources:
#            - name:    New_ReleaseBundle
#              trigger: true
#          outputResources:
#            - name:  Signed_ReleaseBundle

      - name: Sign_ReleaseBundle
        type: bash
        configuration:
          integrations:
            - name: artifactory
            - name: distribution
          inputResources:
            - name:         New_ReleaseBundle
              trigger:      true   # default true
          outputResources:
            - name:         Signed_ReleaseBundle

        execution:
          onStart:
            - printenv
          onExecute:
            - curl -XPOST ${int_artifactory_url}/api/v1/release_bundle/Demo_RB/v1.0.21/sign
          onSuccess:
               - echo "RB was signed"
