pipelines:
  - name: Docker
    steps:
     - name: Gradle_docker_build
       type: DockerBuild
       configuration:
         dockerFileLocation: tutorial/step3-create-docker-multi-app
         dockerFileName: Dockerfile
         dockerImageName: ${int_art_url}/team1-docker/gradle-app
         dockerImageTag: 1
         inputResources:
           - name: orbitera_gitRepo_demo
           - name: gradle_fileSpec
           - name: promoted_gradleBuild_Info
             trigger: true
         integrations:
           - name: art
       execution:
        onStart:
          - mkdir -p tutorial/step3-create-docker-multi-app/package
        onSuccess:
          - ls tutorial/step3-create-docker-multi-app/package
        onFailure:
          - echo "uh oh, something went wrong"
        onComplete: #always
          - echo "Cleaning up some stuff"