pipelines:
  - name: gradle_build
    steps:
      - name: gradle_bld_svc_demo
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
             custom:
              name: docker.bintray.io/jfrog/pipelines-u16java
              tag: "8"
          gradleCommand:        clean artifactoryPublish -b build.gradle
          sourceLocation:       tutorial/step1-create-gradle-app
          configFileLocation:   .
          configFileName:       jfrog-gradle.yml
          forceXrayScan:        false
          autoPublishBuildInfo: true
          inputResources:
            - name: orbitera_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: art
        execution:
          onStart:
            - export artifactory_plugins_url="${int_art_url}"/jcenter-gradle-remote
            - export artifactory_libs_url="${int_art_url}"/team1-gradle
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "Something went terribly wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
            
            
      - name: gradle_scan
        type: XrayScan
        configuration:
          #inherits from bash
          waitUntilFinish: true
          inputResources:
            - name: gradleBuildInfo        
              trigger: true
          outputResources: 
            - name: scanned_gradleBuild_Info
        execution:
          onStart:
            - echo "Preparing to scan artifacts..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
            
                     
      - name: gradle_promote
        type: PromoteBuild
        configuration:
          targetRepository:      team1-gradle-staging-us 
          includeDependencies:   false   
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  true
          inputResources:
            - name:    scanned_gradleBuild_Info    # optional
              trigger: true       
          outputResources:
            - name: promoted_gradleBuild_Info
              

 
       

 
