pipelines:
  - name: npm_build
  # Global configuration section for the entire pipeline
    configuration:
      environmentVariables:
        readOnly:
          ArtIP: $(echo ${int_artifactory_url}|awk -F '/' '{print $3}')
          Version: 1.0.$run_number
    steps:
      - name: npm_compile
        type: NpmBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u18node
                tag: "10.16.3"
          npmArgs:   install
          repositoryName:   team1-npm
          sourceLocation:   tutorial/step2-create-ui-pkg
          integrations:
            - name: artifactory
          inputResources:
            - name: gitRepo_source
        execution:
          onStart:
            - pushd ${res_gitRepo_source_resourcePath}/tutorial/step2-create-ui-pkg
            - npm version ${Version} --no-git-tag-version
            - popd


      - name: npm_pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: npm_compile
          integrations:
            - name: artifactory
        execution:
          onStart:
           # - export tempStateLocation="$step_tmp_dir/npmSourceState/tutorial/step2-create-ui-pkg"
            - export tempStateLocation="${res_gitRepo_source_resourcePath}/tutorial/step2-create-ui-pkg"
            # Restore file from previous step to current step
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm install shelljs
            - npm install
            # Add files to npm pipeline target
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo
            - popd




      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName:       team1-npm
          autoPublishBuildInfo: true
          integrations:
            - name: artifactory
          inputSteps:
            - name: npm_pack_frontend
          outputResources:
            - name: npmBuildInfo
        execution:
          onStart:
            - export inputNpmBuildStepName="npm_compile"


      - name: npm_scan
        type: XrayScan
        configuration:
          #inherits from bash
          waitUntilFinish: true
          inputResources:
            - name: npmBuildInfo        
              trigger: true
          outputResources: 
            - name: scanned_npmBuild_Info
       
         
            
                     
      - name: npm_promote
        type: PromoteBuild
        configuration:
          targetRepository:      team1-npm-staging-us 
          includeDependencies:   false   
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  true
          inputResources:
            - name:    scanned_npmBuild_Info    # optional
              trigger: true       
          outputResources:
            - name: promoted_npmBuild_Info

      - name: npm_docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: tutorial/step2-create-ui-pkg
          dockerFileName: Dockerfile
          dockerImageName: ${ArtIP}/team1-docker-dev-us/npm-app
          dockerImageTag: ${Version}
          inputResources: 
            - name: gitRepo_source
            - name: npm_fileSpec
            - name: promoted_npmBuild_Info
              trigger: true
          integrations:
            - name: artifactory
        execution:
          onStart:
            - printenv
            - pushd ${res_gitRepo_source_resourcePath}/tutorial/step2-create-ui-pkg
            # Creating a Folder for the fileSpec Target
            - mkdir -p npm_results
            - popd
          onSuccess:
            - echo "Congrats The Docker image was build"
        
            


      - name: Npm_docker_push
        type: DockerPush
        configuration:
          targetRepository:     team1-docker-dev-us
          autoPublishBuildInfo: true
          integrations:
            - name:  artifactory
          inputSteps:
            - name: npm_docker_build
          outputResources:
            - name: docker_npmBuild_Info
            
            
      - name: npm_docker_scan
        type: XrayScan
        configuration:
          waitUntilFinish: true
          inputResources:
            - name: docker_npmBuild_Info
              trigger: true
          outputResources: 
            - name: scanned_npm_dockerBuild_Info

      - name: npm_docker_promote
        type: PromoteBuild
        configuration:
          targetRepository:      team1-docker-staging-us 
          includeDependencies:   false   
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  false
          inputResources:
            - name:    scanned_npm_dockerBuild_Info    # optional
              trigger: true       
          outputResources:
            - name: final_docker_npmBuild_Info         
