resources:
  - name: orbitera_gitRepo_demo
    type: GitRepo
    configuration:
      path: yairbass/project-examples
      gitProvider: YairBassGitHub
      branches:
        include: eplus-v2-orbitera

  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: gradle_build
      buildNumber: 1

pipelines:
  - name: demo_pipeline_1_java
    steps:
      - name: gradle_bld_svc_demo
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
             custom:
              name: docker.bintray.io/jfrog/pipelines-u18java
              tag: "8"
          gradleCommand:        clean artifactoryPublish -b build.gradle
          sourceLocation:       tutorial/step1-create-gradle-app
          configFileLocation:   .
          configFileName:       jfrog-gradle.yml
          forceXrayScan:        false
          autoPublishBuildInfo: true
          inputResources:
            - name: orbitera_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: art
        execution:
          onStart:
            - export artifactory_plugins_url="${int_art_url}"/jcenter-gradle-remote
            - export artifactory_libs_url="${int_art_url}"/team1-gradle
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "Something went terribly wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
            




  
