resources:
  - name: orbitera_gitRepo_demo
    type: GitRepo
    configuration:
      path: yairbass/project-examples
      gitProvider: yairbgithub
      branches:
        include: eplus-v2-orbitera

  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: gradle_build
      buildNumber: 1

pipelines:
  - name: gradle_build
    steps:
      - name: gradle_bld_svc_demo
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          gradleCommand:        clean artifactoryPublish -b build.gradle
          sourceLocation:       tutorial/step1-create-gradle-app
          configFileLocation:   .
          configFileName:       grade.properties
          forceXrayScan:        false
          autoPublishBuildInfo: true
          inputResources:
            - name: orbitera_gitRepo_demo
          outputResources:
            - name: gradle_build_info
          integrations:
            - name: art
        execution:
          onStart:
            - ls -ltr
            - pwd
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
            
      - name: publish_svc_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: gradle_bld_svc_demo
          outputResources:
            - name: svc_build_info_demo



  
