resources:
  - name: orbitera_gitRepo_demo
    type: GitRepo
    configuration:
      path: yairbass/project-examples
      gitProvider: YairBassGitHub
      branches:
        include: eplus-v2-orbitera

  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: gradle_build
      buildNumber: 1

pipelines:
  - name: demo_pipeline_1_java
    steps:
      - name: gradle_bld_svc_demo
        type: GradleBuild
        configuration:
          gradleCommand:        clean artifactoryPublish -b build.gradle
          sourceLocation:       tutorial/step1-create-gradle-app
          configFileLocation:   .
          configFileName:       gradle.properties
          forceXrayScan:        false
          autoPublishBuildInfo: true
          inputResources:
            - name: orbitera_gitRepo_demo
          outputResources:
            - name: gradleBuildInfo
          integrations:
            - name: art
        execution:
          onStart:
            - cd $res_orbitera_gitRepo_demo_resourcePath
            - pwd
            - ls -ltr
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
            
#       - name: publish_svc_build_demo
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: gradleBuildInfo
#           outputResources:
#             - name: svc_build_info_demo



  
